# The URL the site will be built for
base_url = "https://mvlabat.github.io"

title = "Vladyslav Batyrenko"
# a description; you can use markdown here if you like
description=""
# description="\"*I don't have a quote for you (like in the [Ergo theme](https://www.getzola.org/themes/ergo/)), but I'll just say here that it's my personal blog, and it should be mostly about my [Grumpy Visitors](https://github.com/amethyst/grumpy_visitors) game and programming*\" - mvlabat, aka Mr. Blyat (not widely really)"
default_language = "en"

theme = "ergo"

highlight_theme = "solarized-light"
generate_rss = true
rss_limit = 20

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[extra]
# theme options, (Submit an issue if any social network you may want is missing here: https://github.com/InsidiousMind/Ergo/issues)
profile = "avatar_115px.jpg" # the name of the profile picture in static/img/
website = "mvlabat.github.io"
github = "mvlabat"
twitter = "mvlabat"
linkedin = "mvlabat"
email = "mvlabat@gmail.com"
# instagram = ""
# keybase = ""
# reddit = ""
# youtube = ""
