name: Zola

on: [push, pull_request]

jobs:
  zola:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://github.com/getzola/zola/releases/download
      VERS: v0.9.0
      ARCH: x86_64-unknown-linux-gnu
      # https://github.com/marketplace/actions/github-pages#warning-limitation
      GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install Zola
      run: curl -L ${BASE_URL}/${VERS}/zola-${VERS}-${ARCH}.tar.gz | tar -xz
    - run: ./zola --version
    - run: ./zola build
    - name: Deploy
      if: github.ref == 'refs/heads/code'
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_PAT }}
        publish_dir: ./public
        publish_branch: master
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
